# Generated by Django 2.1.5 on 2019-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_kpi_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='change',
            field=models.CharField(choices=[('>', 'Percentage Increase'), ('=', 'Equals'), ('<', 'Percentage Decrease')], default='=', max_length=1),
        ),
    ]
