# Generated by Django 2.1.5 on 2019-03-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20190303_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
