# Generated by Django 2.1.5 on 2019-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_kpi_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='current',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target',
            field=models.BigIntegerField(),
        ),
    ]
