# Generated by Django 2.1.5 on 2019-03-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_auto_20190303_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalallocation',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Team'),
        ),
    ]
