# Generated by Django 2.1.5 on 2019-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190219_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposition',
            name='start',
            field=models.DateField(),
        ),
    ]
