# Generated by Django 2.1.5 on 2019-03-07 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kudos',
            new_name='Kudo',
        ),
    ]
