# Generated by Django 2.1.5 on 2019-02-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=2083)),
                ('branches', models.BooleanField(default=0)),
                ('cf_frequency', models.IntegerField()),
                ('created', models.DateTimeField(verbose_name='date_created')),
                ('updated', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
