# Generated by Django 2.1.5 on 2019-02-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20190215_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='branches',
        ),
    ]
