# Generated by Django 2.1.5 on 2019-02-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_userposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userposition',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPosition',
        ),
    ]
