# Generated by Django 2.1.5 on 2019-02-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_remove_organisation_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='branches',
            field=models.BooleanField(default=0),
        ),
    ]
