# Generated by Django 2.1.5 on 2019-03-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='onboarding.Kit'),
            preserve_default=False,
        ),
    ]
