# Generated by Django 2.1.5 on 2019-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_task_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
